#!/usr/bin/env python3
"""Render THE ARK field communications plan and conservative Reticulum config."""
from __future__ import annotations

import argparse
import pathlib
import yaml


def load(path: pathlib.Path) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if data.get("schema") != 1:
        raise ValueError("unsupported field-comms schema")
    if not data.get("region"):
        raise ValueError("region is required")
    return data


def reticulum(data: dict) -> str:
    r = data.get("reticulum") or {}
    transport = "Yes" if r.get("enable_transport", False) else "No"
    enabled = "Yes" if r.get("auto_interface", True) else "No"
    return f"""# Generated by THE ARK. Review before field deployment.
[reticulum]
  enable_transport = {transport}
  share_instance = Yes

[logging]
  loglevel = 4

[interfaces]
  [[Ark AutoInterface]]
    type = AutoInterface
    enabled = {enabled}
"""


def markdown(data: dict) -> str:
    region = data["region"]
    meshtastic = data.get("meshtastic") or {}
    sdr = data.get("sdr") or {}
    return f"""# THE ARK Field Communications Plan

**Regulatory region:** {region}

This plan is intentionally frequency-agnostic. Configure radio frequencies,
power and licensing according to the local regulator and hardware.

## Layer 1 — local IP

Use Ethernet first. If supported by the Wi-Fi chipset, THE ARK can provide its
local access point and captive/local portal.

## Layer 2 — Reticulum

- AutoInterface: {'enabled' if (data.get('reticulum') or {}).get('auto_interface', True) else 'disabled'}
- Transport node: {'enabled' if (data.get('reticulum') or {}).get('enable_transport', False) else 'disabled by default'}
- Runtime check: `rnstatus`

Generated config: `state/field/reticulum.conf`.

## Layer 3 — Meshtastic

- Intended role: {meshtastic.get('role', 'CLIENT')}
- Android APK and firmware are preserved by supported profiles.
- Pair/configure radios locally; never assume Internet or cloud MQTT exists.

## Layer 4 — SDR / satellite receive

- Receive-only default: {str(bool(sdr.get('receive_only', True))).lower()}
- SatDump and rtl-sdr source are preserved in NOMAD/CIVILIZATION.
- Use receive-only workflows until the operator has confirmed local radio rules.
- Candidate workflow: satellite weather/data reception with locally supported hardware.

## Field rule

Prefer the lowest-dependency path that works:

```text
Ethernet/LAN → Wi-Fi AP → Reticulum/Meshtastic → receive-only SDR information
```

Do not expose Ark services directly to the public Internet as a substitute for a
field network design.
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("render")
    r.add_argument("--config", required=True)
    r.add_argument("--out", required=True)
    c = sub.add_parser("reticulum-config")
    c.add_argument("--config", required=True)
    c.add_argument("--out", required=True)
    k = sub.add_parser("check")
    k.add_argument("--config", required=True)
    args = ap.parse_args()
    data = load(pathlib.Path(args.config))
    if args.cmd == "check":
        print(f"OK: {data['region']}")
        return 0
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(markdown(data) if args.cmd == "render" else reticulum(data), encoding="utf-8")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
